import { StyleSheet } from 'react-native'

const colours = {
    activeButton: 'hsl(270, 70%, 60%)',
    darkMain: 'hsl(270, 44%, 7%)',
    darkDetail: 'hsl(270, 35%, 12%)',
    lightDetail: 'hsl(270, 34%, 69%)',
    lightEmphasis: 'hsl(24, 65%, 99%)',
    lightMain: 'hsl(320, 15%, 90%)',
}

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    main: {
        backgroundColor: colours.darkMain,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-start',
        padding: 30,
    },
    menu: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
        width: 310,
    },
    label: {
        color: colours.lightMain,
        fontSize: 18,
    },
    labelBold: {
        color: colours.lightMain,
        fontSize: 18,
        fontWeight: 'bold',
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        margin: 4,
        width: 310,
    },
    textInput: {
        backgroundColor: colours.darkDetail,
        borderRadius: 20,
        color: colours.lightMain,
        fontSize: 18,
        margin: 4,
        padding: 15,
        paddingLeft: 30,
        paddingRight: 30,
        width: 310,
    },
    timeInput: {
        backgroundColor: colours.darkDetail,
        padding: 15,
        paddingLeft: 30,
        paddingRight: 30,
    },
    title: {
        alignSelf: 'flex-start',
        color: colours.lightEmphasis,
        fontSize: 25,
        fontWeight: 'bold',
    },
    touchable: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: colours.darkDetail,
        borderRadius: 30,
        margin: 4,
        padding: 15,
        width: 310,
    },
    touchableActive: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: colours.activeButton,
        borderRadius: 30,
        margin: 8,
        padding: 15,
        width: 310,
    },
    touchMenu: {
        alignItems: 'center',
        backgroundColor: colours.darkDetail,
        borderRadius: 30,
        marginLeft: 5,
        marginRight: 5,
        padding: 5,
        width: 130,
    },
    touchMenuActive: {
        alignItems: 'center',
        backgroundColor: colours.activeButton,
        borderRadius: 30,
        marginLeft: 5,
        marginRight: 5,
        padding: 5,
        width: 130,
    },
    touchButton: {
        backgroundColor: colours.darkDetail,
        padding: 15,
        paddingLeft: 20,
        paddingRight: 20,
    },
    touchMinus: {
        borderTopLeftRadius: 30,
        borderBottomLeftRadius: 30,
    },
    touchPlus: {
        borderTopRightRadius: 30,
        borderBottomRightRadius: 30,
    },
})
